### ISSUE TITLE
task-name

### ISSUE THREAD

**Issue by Dlinuigh** [luxinyu1/Trans-SS#1]
我在跑你们的代码的时候，碰到了些问题，首先我想问的是`test.py`的参数`--task-name`应该是什么内容。

**Comment by luxinyu1** [comment]
> 我在跑你们的代码的时候，碰到了些问题，首先我想问的是`test.py`的参数`--task-name`应该是什么内容。

您好，感谢您的issue。应为对应数据集经过fairseq预处理后的数据目录名称中在"ts-"和"-bin"中间的字段。

可以参考`test.py`的163行：`    args.data = str(REPO_DIR) + "/ts-" + args.task_name + "-bin/"`
